site_name: rnnsim
site_description: Random Neural Network Simulator implemented in Python.
site_author: Mandar Gogate

repo_url: https://github.com/MandarGogate/RNNSim
edit_uri: https://github.com/MandarGogate/RNNSim/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: true

nav:
  - Home: index.md
  - Examples: examples.md
  - About:
      - Release Notes: about/changelog.md
      - Contributing: about/contributing.md
      - License: about/license.md
